---
- name: Deploy the Mysql role to server and configure
  hosts: db
  remote_user: root
  gather_facts: false
  tasks:
    - name: update system
      dnf:
        name: "*"
        state: "latest"
    - name: install mysql and components
      dnf:
        name: "mariadb-server, mariadb"
        state: "present"
    - name: Enable the MySQL service
      service:
        name: mariadb
        state: started
        enabled: True
    - name: Open MySQL ports
      firewalld:
        zone: public
        service: mysql
        immediate: yes
        #port: 3306/tcp
        permanent: true
        state: enabled

    - name: Enable the Firewall Service
      service:
        name: firewalld
        state: restarted
        enabled: True
    - name: Set new root password
      block:
        - name: See if password has changed
          stat:
            path: /root/.mysqlpasschg
          register: stat_result
        - name: File not found changing default password
          shell: "mysql -u root -e \"SET PASSWORD FOR root@'localhost' = PASSWORD('{{ mysql_root_password }}');\" " 
          ignore_errors: yes
          when: not stat_result.stat.exists
          no_log: true
        - name: Create file in place
          file:
            path: /root/.mysqlpasschg
            group: root
            owner: root
            state: touch
          when: not stat_result.stat.exists

    - name: Preparing the DATABASE and Creating User accounts
      command: "{{ item }}"
      no_log: true 
      loop:
        - "mysql -u root -p'{{ mysql_root_password }}' -e \"CREATE DATABASE demoapp1;\" "
        - "mysql -u root -p'{{ mysql_root_password }}' -e \"CREATE USER '{{ mysql_db_user }}'@'%' IDENTIFIED BY '{{ mysql_db_password }}';\" "
        - "mysql -u root -p'{{ mysql_root_password }}' -e \"GRANT ALL PRIVILEGES ON demoapp1.* TO '{{ mysql_db_user }}'@'%';\" "
        - "mysql -u root -p'{{ mysql_root_password }}' -e \"FLUSH PRIVILEGES\" "
      ignore_errors: yes
    - name: Populating Database
      command: "mysql -D demoapp1 -u {{ mysql_db_user }} -p'{{ mysql_db_password }}' -e \"{{ item }}\" "
      no_log: true 
      loop:
        - "create table joke_table (JokeID INT AUTO_INCREMENT KEY, Joke_question VARCHAR(500), Joke_answer VARCHAR(500));"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'What time is it when an elephant sits on your fence?','Time to buy a new fence');"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'Why did the chicken cross the road?','To get to the other side');"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'What is brown and sticky','A stick');"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'Why did the chicken cross the playground','To get to the other slide');"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'What happens to a frogs car when it breaks down?','It gets toad away');"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'How does a frog start his car when the battery is dead','He gets a jump start');"
        - "INSERT INTO joke_table (JokeID,Joke_question,Joke_answer) VALUES(null,'What did the mother buffalo say to her sone when she dropped him off at school?','Bison');"
      ignore_errors: yes
